name: Reusable Possible Bot Comment

on:
  workflow_call:
    inputs:
      label:
        description: 'Label name that triggers the comment'
        type: string
        default: 'possible bot'
      comment:
        description: 'Markdown comment body to post on the issue or PR'
        type: string
        required: true

jobs:
  comment:
    name: Comment on issue or PR
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Post possible bot comment
        if: github.event.label.name == inputs.label
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const item = context.payload.issue || context.payload.pull_request
            const isPR = !!context.payload.pull_request

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: item.number,
              body: ${{ toJSON(inputs.comment) }},
            })

            core.summary
              .addHeading('Possible bot comment', 2)
              .addTable([
                [{ data: 'Property', header: true }, { data: 'Value', header: true }],
                ['Issue/PR', `#${item.number}`],
                ['Type', isPR ? 'Pull Request' : 'Issue'],
                ['Label', '${{ inputs.label }}'],
              ])
              .addRaw('\n\nPosted AI contribution policy comment.')

            await core.summary.write()
